[package]
name = "portaudio-example"
version = "0.1.0"
authors = ["ernst"]

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
portaudio       = { git = "https://github.com/mvdnes/portaudio-rs" }

